# Site settings
title: Sagamore
email: fayne@mobilenowgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/sagamore" # the subpath of your site, e.g. /blog/
url: "http://fayne-mobilenow.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
env: "dev"

#Exclude
exclude: ['node_modules', 'Gruntfile.js', 'package.json', 'npm-debug.log']

# Build settings
markdown: kramdown

# Collections
collections:
  - team
  - features
  - work
  - slider
  - fund_investments
  - direct_investments
  - contact

#permalink
permalink:   /:categories/:title/

prose:
  rooturl: ''
  siteurl: 'http://fayne-mobilenow.github.io/sagamore/'
  relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'images'
  ignore:
    - /_layouts
    - /_sass
    - /_includes
    - /css
    - /js
    - /.gitignore
    - /about.md
    - feed.xml
    - package.json
    - Gruntfile.js
 